### ISSUE TITLE
Not possible to add a subscription with only Cloud Native Protection

### ISSUE THREAD

**Issue by johan3141592** [rubrikinc/terraform-azure-polaris-cloud-native_subscription#1]
**Expected Behavior**
Setting `enable_exocompute` to `false` and not specifying `exocompute_details` should add the subscription for Cloud Native Protection only.

**Current Behavior**
The `polaris_azure_subscription` resource fails to be created because `regions`, of the `exocompute` parameter, is an empty list. Specifying `exocompute_details` but keeping `enable_exocompute` as `false` leads to the subscription being added with the Exocompute feature turned on, but the principal missing permissions for Exocompute and no Exocompute configuration being created.

**Comment by DamaniN** [comment]
Fix #2  provided by @johan3141592
