### ISSUE TITLE
Support for Granular Permissions control

### ISSUE THREAD

**Issue by joeharlan** [rubrikinc/terraform-azure-polaris-cloud-native_subscription#3]
**Is your feature request related to a problem? Please describe.**

Organizations seeking strict control over privileged access to cloud resources are eager to use our Granular Permissions model to achieve Zero Trust operations of Rubrik Security Cloud.  For organizations that follow a strictly IaC approach for cloud deployments this feature is required for DevOps.

**Describe the solution you'd like**

Enable full control of Granular Permissions for Azure including enabling and disabling the permissions as needed for ongoing RSC operations as follows.

Protection:
- Azure VM/Managed Disks & Apps:  Export and Restore, File-level Recovery, Cloud Cluster
- Azure SQL DB & Managed Instances: Recovery, Immutable Backups
Archive & Storage:  
- Cloud Native Archive: Encryption

Rubrik Documentation Reference:  https://docs.rubrik.com/en-us/saas/saas/granular_manage_azr_perm_categories.html

**Describe alternatives you've considered**

**Additional context**

**Comment by joeharlan** [comment]
This capability and its support is best tracked under the Provider rather than the module.  It is also noted that the general toggling of permissions is handled during recovery actions that would otherwise not be executed with TF.  Closing this issue.

**Comment by johan3141592** [comment]
Support for Azure subscriptions granular permissions is available since version `v1.0.0` of the RSC provider. Support is not yet added to this module.
